FROM python:3.9-alpine3.16

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /server

COPY requirements.txt /temp/requirements.txt

RUN apk add postgresql-client build-base postgresql-dev

RUN pip install --upgrade pip \
    && pip install -r /temp/requirements.txt \
    && rm -rf /root/.cache

COPY server /server

EXPOSE 8000