# Generated by Django 3.2.16 on 2024-11-29 12:18

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Узбекский о тексте')),
                ('text_en', ckeditor.fields.RichTextField(verbose_name='Текст на английском')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Текст на русском')),
            ],
            options={
                'verbose_name': 'О деталях',
                'verbose_name_plural': 'О деталях',
            },
        ),
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Узбекский заголовок деятельности')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Русский заголовок деятельности')),
                ('title_en', models.CharField(max_length=200, verbose_name='Английский заголовок деятельности')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Узбекский текст о деятельности')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Русский текст о деятельности')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Текст о деятельности на английском')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельность',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Заголовок на узбекском')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок на русском')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок на английском')),
                ('text_uz', models.TextField(verbose_name='Текст на узбекском')),
                ('text_ru', models.TextField(verbose_name='Текст на русском')),
                ('text_en', models.TextField(verbose_name='Текст на английском')),
                ('body_uz', ckeditor.fields.RichTextField(verbose_name='Основной текст на узбекском')),
                ('body_ru', ckeditor.fields.RichTextField(verbose_name='Основной текст на русском')),
                ('body_en', ckeditor.fields.RichTextField(verbose_name='Основной текст на английском')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='ApparatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение аппарата')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Узбекский заголовок аппарата')),
                ('title_en', models.CharField(max_length=300, verbose_name='Заголовок аппарата на английском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Русский заголовок аппарата')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Изображение кандидата')),
                ('fio_ru', models.CharField(max_length=200, verbose_name='Полное имя кандидата на русском (Фамилия, Имя, Отчество)')),
                ('fio_en', models.CharField(max_length=200, verbose_name='Полное имя кандидата на английском (Фамилия, Имя, Отчество)')),
                ('fio_uz', models.CharField(max_length=200, verbose_name='Полное имя кандидата на узбекском (Фамилия, Имя, Отчество)')),
                ('organized_date', models.DateField(verbose_name='Год основания')),
                ('in_position', models.DateField(verbose_name='Дата начала работы кандидата')),
                ('position_ru', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на русском')),
                ('position_en', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на английском')),
                ('position_uz', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на узбекском')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Узбекское дополнительное описание')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Дополнительное описание на английском')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Русское дополнительное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Аппарат',
                'verbose_name_plural': 'Аппарат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение баннера')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Узбекский заголовок баннера')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Русский заголовок баннера')),
                ('title_en', models.CharField(max_length=500, verbose_name='Заголовок баннера на английском')),
                ('text_uz', models.TextField(verbose_name='Узбекский текст баннера')),
                ('text_ru', models.TextField(verbose_name='Русский текст баннера')),
                ('text_en', models.TextField(verbose_name='Текст баннера на английском')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Баннеры',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('addrees', models.CharField(max_length=200, verbose_name='Адрес')),
                ('facebook', models.CharField(max_length=200, verbose_name='Ссылка на Facebook')),
                ('telegram', models.CharField(max_length=200, verbose_name='Ссылка на Telegram')),
                ('instagram', models.CharField(max_length=200, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='FinanceFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('size', models.CharField(max_length=100, verbose_name='Размер файла')),
                ('file_name_uz', models.CharField(max_length=1000, verbose_name='Узбекское имя файла')),
                ('file_name_ru', models.CharField(max_length=1000, verbose_name='Русское имя файла')),
                ('file_name_en', models.CharField(max_length=1000, verbose_name='Английское имя файла')),
            ],
            options={
                'verbose_name': 'Финансовые документы',
                'verbose_name_plural': 'Финансовые документы',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name="Узбекский заголовок раздела 'О нас' на главной странице")),
                ('title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name="Заголовок раздела 'О нас' на главной странице на английском")),
                ('title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name="Русский заголовок раздела 'О нас' на главной странице")),
                ('text1_uz', models.TextField(blank=True, null=True, verbose_name="Узбекский текст первого абзаца раздела 'О нас' на главной странице")),
                ('text1_en', models.TextField(blank=True, null=True, verbose_name="Текст первого абзаца раздела 'О нас' на главной странице на английском")),
                ('text1_ru', models.TextField(blank=True, null=True, verbose_name="Текст первого абзаца раздела 'О нас' на главной странице на русском")),
                ('text2_uz', models.TextField(blank=True, null=True, verbose_name="Узбекский текст второго абзаца раздела 'О нас' на главной странице")),
                ('text2_en', models.TextField(blank=True, null=True, verbose_name="Текст второго абзаца раздела 'О нас' на главной странице на английском")),
                ('text2_ru', models.TextField(blank=True, null=True, verbose_name="Текст второго абзаца раздела 'О нас' на главной странице на русском")),
            ],
            options={
                'verbose_name': 'Главная О на',
                'verbose_name_plural': 'Главная О на',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение лаборатории')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Узбекский заголовок лаборатории')),
                ('title_en', models.CharField(max_length=300, verbose_name='Заголовок лаборатории на английском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Русский заголовок лаборатории')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Изображение кандидата')),
                ('fio_ru', models.CharField(max_length=200, verbose_name='Полное имя кандидата на русском (Фамилия, Имя, Отчество)')),
                ('fio_en', models.CharField(max_length=200, verbose_name='Полное имя кандидата на английском (Фамилия, Имя, Отчество)')),
                ('fio_uz', models.CharField(max_length=200, verbose_name='Полное имя кандидата на узбекском (Фамилия, Имя, Отчество)')),
                ('organized_date', models.DateField(verbose_name='Год основания')),
                ('in_position', models.DateField(verbose_name='Дата начала работы кандидата')),
                ('position_ru', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на русском')),
                ('position_en', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на английском')),
                ('position_uz', models.CharField(max_length=100, verbose_name='Род деятельности кандидата на узбекском')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Узбекское дополнительное описание')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Дополнительное описание на английском')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Русское дополнительное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатория',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalStatusFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('size', models.CharField(max_length=100, verbose_name='Размер файла')),
                ('file_name_uz', models.CharField(max_length=1000, verbose_name='Узбекское имя файла')),
                ('file_name_ru', models.CharField(max_length=1000, verbose_name='Русское имя файла')),
                ('file_name_en', models.CharField(max_length=1000, verbose_name='Английское имя файла')),
            ],
            options={
                'verbose_name': 'Файлы юридического статуса',
                'verbose_name_plural': 'Файлы юридического статуса',
            },
        ),
        migrations.CreateModel(
            name='LegalStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Узбекский текст юридического статуса')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Русский текст юридического статуса')),
                ('text_en', ckeditor.fields.RichTextField(verbose_name='Текст юридического статуса на английском')),
            ],
            options={
                'verbose_name': 'Юридический статус',
                'verbose_name_plural': 'Юридический статус',
            },
        ),
        migrations.CreateModel(
            name='MailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('sended_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ('Сообщения',),
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-sended_time'],
            },
        ),
        migrations.CreateModel(
            name='OpenDataFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('size', models.CharField(max_length=100, verbose_name='Размер файла')),
                ('file_name_uz', models.CharField(max_length=1000, verbose_name='Узбекское имя файла')),
                ('file_name_ru', models.CharField(max_length=1000, verbose_name='Русское имя файла')),
                ('file_name_en', models.CharField(max_length=1000, verbose_name='Английское имя файла')),
            ],
            options={
                'verbose_name': 'Файлы открытых данных',
                'verbose_name_plural': 'Файлы открытых данных',
            },
        ),
        migrations.CreateModel(
            name='PicturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images/', verbose_name='Изображение услуги')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Узбекский заголовок услуги')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Русский заголовок услуги')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок услуги на английском')),
                ('text_uz', ckeditor.fields.RichTextField(verbose_name='Узбекский текст услуги')),
                ('text_en', ckeditor.fields.RichTextField(verbose_name='Текст услуги на английском')),
                ('text_ru', ckeditor.fields.RichTextField(verbose_name='Русский текст услуги')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет фона услуги')),
            ],
            options={
                'verbose_name': 'Сервисы',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Узбекский заголовок статистики')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок статистики на английском')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Русский заголовок статистики')),
                ('count', models.IntegerField(verbose_name='Количество статистики')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение структуры')),
            ],
            options={
                'verbose_name': 'Схема структуры',
                'verbose_name_plural': 'Схема структуры',
            },
        ),
        migrations.CreateModel(
            name='StructureFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('size', models.CharField(max_length=100, verbose_name='Размер файла')),
                ('file_name_uz', models.CharField(max_length=1000, verbose_name='Узбекское имя файла')),
                ('file_name_ru', models.CharField(max_length=1000, verbose_name='Русское имя файла')),
                ('file_name_en', models.CharField(max_length=1000, verbose_name='Английское имя файла')),
            ],
            options={
                'verbose_name': 'Структура документа',
                'verbose_name_plural': 'Структура документа',
            },
        ),
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение для полезной ссылки')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Узбекский заголовок полезной ссылки')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок полезной ссылки на английском')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Русский заголовок полезной ссылки')),
                ('url', models.URLField(verbose_name='Полезная ссылка')),
            ],
            options={
                'verbose_name': 'Полезные ссылки',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_uz', models.CharField(max_length=200, verbose_name='Узбекское название дня недели')),
                ('week_ru', models.CharField(max_length=200, verbose_name='Русское название дня недели')),
                ('week_en', models.CharField(max_length=200, verbose_name='Название дня недели на английском')),
            ],
            options={
                'verbose_name': 'Дни недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Узбекский заголовок галереи')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок галереи на английском')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Русский заголовок галереи')),
                ('picture_count', models.IntegerField(default=0, verbose_name='Количество изображений в галерее')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pictures', models.ManyToManyField(blank=True, to='main.PicturesModel', verbose_name='Изображения галереи')),
            ],
            options={
                'verbose_name': 'Галереи',
                'verbose_name_plural': 'Галереи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Узбекский заголовок новости')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок новости на английском')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Русский заголовок новости')),
                ('description_uz', models.TextField(verbose_name='Узбекский текст новости')),
                ('description_en', models.TextField(verbose_name='Текст новости на английском')),
                ('description_ru', models.TextField(verbose_name='Русский текст новости')),
                ('popular', models.BooleanField(default=False, verbose_name='Популярно?')),
                ('picture_count', models.IntegerField(default=0, verbose_name='Количество изображений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pictures', models.ManyToManyField(blank=True, to='main.PicturesModel', verbose_name='Изображения новости')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Узбекское полное имя (Имя, Фамилия и Отчество)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Русское полное имя (Имя, Фамилия и Отчество)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Английское полное имя (Имя, Фамилия и Отчество)')),
                ('position_uz', models.CharField(max_length=200, verbose_name='Узбекская должность')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Русская должность')),
                ('position_en', models.CharField(max_length=200, verbose_name='Английская должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефонный номер')),
                ('admission_start_time', models.TimeField(verbose_name='Время начала приема')),
                ('admission_end_time', models.TimeField(verbose_name='Время окончания приема')),
                ('bio_uz', models.TextField(verbose_name='Узбекская биография')),
                ('bio_ru', models.TextField(verbose_name='Русская биография')),
                ('bio_en', models.TextField(verbose_name='Английская биография')),
                ('admission_days', models.ManyToManyField(blank=True, to='main.Weekend', verbose_name='Выберите дни приема')),
            ],
            options={
                'verbose_name': 'Руководители',
                'verbose_name_plural': 'Руководители',
            },
        ),
    ]
