from django.urls import path
from .views import *


urlpatterns = [
    path("news-detail/<int:pk>/", GetOneNewsView.as_view()),
    path("galery-detail/<int:pk>/", GetOneGaleryView.as_view()),
    path("service-detail/<int:pk>/", GetOneServiceView.as_view()),
    path("banner-detail/<int:pk>/", GetOneBannerView.as_view()),
    path("usefull-link-detail/<int:pk>/", GetOneUsefullView.as_view()),
    path("mail-detail/<int:pk>/", GetDetailMail.as_view()),
    path("apparat-detail/<int:pk>/", GetApparatView.as_view()),
    path("laboratory-detail/<int:pk>/", GetLaboratoryView.as_view()),
    path("announce-detail/<int:pk>/", GetAnnounceView.as_view()),
    path("activity-detail/<int:pk>/", GetOneActivity.as_view()),
    path("news/", NewsView.as_view()),
    path("galery/", PhotoGaleryView.as_view()),
    path("service/", ServiceView.as_view()),
    path("contact/", ContactView.as_view()),
    path("banner/", BannerView.as_view()),
    path("home-about/", HomeAboutView.as_view()),
    path("about-detail/", AboutView.as_view()),
    path("statistics/", StatisticsView.as_view()),
    path("popular-news/", PopularNewsView.as_view()),
    path("usefull-links/", UsefulLinksView.as_view()),
    path("mail/", MailView.as_view()),
    path("disactive-mails/", GetDisactiveMailsView.as_view()),
    path("laboratory/", LaboratoryView.as_view()),
    path("apparats/", ApparatView.as_view()),
    path("structure-img/", StructureVIew.as_view()),
    path("home-news/", LastFiveNews.as_view()),
    path("structure-files/", StructureFilesView.as_view()),
    path("open-data-files/", OpenDataFilesView.as_view()),
    path("finance-files/", FinanceFilesView.as_view()),
    path("legal-status/", LegalStatusView.as_view()),
    path("corruption-files/", CorruptionFilesView.as_view()),
    path("legal-status-files/", LegalStatusFilesView.as_view()),
    path("activity/", ActivityView.as_view()),
    path("weekend/", WeekendView.as_view()),
    path("management/", ManagementView.as_view()),
    path("management/<int:pk>/", GetOneManagmentView.as_view()),
    path("news-filter/", FilterNews.as_view()),
    path("announcements/", AnnounceView.as_view()),
    path("home-announce/", HomeAnnounceView.as_view()),
    path("home-galeries/", GetThreeGalery.as_view()),
    path("partners/", PartnerView.as_view()),
    path("corruption/", CorruptionView.as_view()),
]
